
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARGUMENT ASIGN METHOD NEWLINE RPAREN VARIABLEstatement : ASIGN expression : METHOD RPARENexpression : ARGUMENTexpression : VARIABLE'
    
_lr_action_items = {'ASIGN':([0,],[2,]),'$end':([1,2,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ASIGN','statement',1,'p_statement_assign','pilas.py',6),
  ('expression -> METHOD RPAREN','expression',2,'p_expression_method','pilas.py',10),
  ('expression -> ARGUMENT','expression',1,'p_expression_arg','pilas.py',14),
  ('expression -> VARIABLE','expression',1,'p_expression_var','pilas.py',18),
]
